var easy_med = {   "verses" : [{},
{"canonical" : "John 3:16", "passages": ["\"For God so loved the world, that he gave his only Son, that whoever believes in him should not perish but have eternal life. (ESV)"], "query": "043003016"},
{"canonical" : "John 1:1", "passages": ["In the beginning was the Word, and the Word was with God, and the Word was God. (ESV)"], "query": "043001001"},
{"canonical" : "John 14:6", "passages": ["Jesus said to him, \"I am the way, and the truth, and the life. No one comes to the Father except through me. (ESV)"], "query": "043014006"},
{"canonical" : "Matthew 28:19", "passages": ["Go therefore and make disciples of all nations, baptizing them in the name of the Father and of the Son and of the Holy Spirit, (ESV)"], "query": "040028019"},
{"canonical" : "Romans 3:23", "passages": ["for all have sinned and fall short of the glory of God, (ESV)"], "query": "045003023"},
{"canonical" : "Ephesians 2:8", "passages": ["For by grace you have been saved through faith. And this is not your own doing; it is the gift of God, (ESV)"], "query": "049002008"},
{"canonical" : "Genesis 1:1", "passages": ["In the beginning, God created the heavens and the earth. (ESV)"], "query": "001001001"},
{"canonical" : "Acts 1:8", "passages": ["But you will receive power when the Holy Spirit has come upon you, and you will be my witnesses in Jerusalem and in all Judea and Samaria, and to the end of the earth.\" (ESV)"], "query": "044001008"},
{"canonical" : "2 Timothy 3:16", "passages": ["All Scripture is breathed out by God and profitable for teaching, for reproof, for correction, and for training in righteousness, (ESV)"], "query": "055003016"},
{"canonical" : "Romans 10:9", "passages": ["because, if you confess with your mouth that Jesus is Lord and believe in your heart that God raised him from the dead, you will be saved. (ESV)"], "query": "045010009"},
{"canonical" : "Romans 6:23", "passages": ["For the wages of sin is death, but the free gift of God is eternal life in Christ Jesus our Lord. (ESV)"], "query": "045006023"},
{"canonical" : "John 1:12", "passages": ["But to all who did receive him, who believed in his name, he gave the right to become children of God, (ESV)"], "query": "043001012"},
{"canonical" : "Romans 8:28", "passages": ["And we know that for those who love God all things work together for good, for those who are called according to his purpose. (ESV)"], "query": "045008028"},
{"canonical" : "John 1:9", "passages": ["The true light, which enlightens everyone, was coming into the world. (ESV)"], "query": "043001009"},
{"canonical" : "Genesis 1:26", "passages": ["Then God said, \"Let us make man in our image, after our likeness. And let them have dominion over the fish of the sea and over the birds of the heavens and over the livestock and over all the earth and over every creeping thing that creeps on the earth.\" (ESV)"], "query": "001001026"},
{"canonical" : "Romans 12:1", "passages": ["I appeal to you therefore, brothers, by the mercies of God, to present your bodies as a living sacrifice, holy and acceptable to God, which is your spiritual worship. (ESV)"], "query": "045012001"},
{"canonical" : "Romans 5:8", "passages": ["but God shows his love for us in that while we were still sinners, Christ died for us. (ESV)"], "query": "045005008"},
{"canonical" : "John 3:3", "passages": ["Jesus answered him, \"Truly, truly, I say to you, unless one is born again he cannot see the kingdom of God.\" (ESV)"], "query": "043003003"},
{"canonical" : "Philippians 4:13", "passages": ["I can do all things through him who strengthens me. (ESV)"], "query": "050004013"},
{"canonical" : "Philippians 4:6", "passages": ["do not be anxious about anything, but in everything by prayer and supplication with thanksgiving let your requests be made known to God. (ESV)"], "query": "050004006"},
{"canonical" : "John 1:3", "passages": ["All things were made through him, and without him was not any thing made that was made. (ESV)"], "query": "043001003"},
{"canonical" : "Galatians 2:20", "passages": ["I have been crucified with Christ. It is no longer I who live, but Christ who lives in me. And the life I now live in the flesh I live by faith in the Son of God, who loved me and gave himself for me. (ESV)"], "query": "048002020"},
{"canonical" : "Mark 16:15", "passages": ["And he said to them, \"Go into all the world and proclaim the gospel to the whole creation. (ESV)"], "query": "041016015"},
{"canonical" : "John 10:10", "passages": ["The thief comes only to steal and kill and destroy. I came that they may have life and have it abundantly. (ESV)"], "query": "043010010"},
{"canonical" : "John 1:14", "passages": ["And the Word became flesh and dwelt among us, and we have seen his glory, glory as of the only Son from the Father, full of grace and truth. (ESV)"], "query": "043001014"},
{"canonical" : "Acts 4:12", "passages": ["And there is salvation in no one else, for there is no other name under heaven given among men by which we must be saved.\" (ESV)"], "query": "044004012"},
{"canonical" : "Galatians 5:22", "passages": ["But the fruit of the Spirit is love, joy, peace, patience, kindness, goodness, faithfulness, (ESV)"], "query": "048005022"},
{"canonical" : "Proverbs 3:5", "passages": ["Trust in the LORD with all your heart, and do not lean on your own understanding. (ESV)"], "query": "020003005"},
{"canonical" : "Jeremiah 29:11", "passages": ["For I know the plans I have for you, declares the LORD, plans for wholeness and not for evil, to give you a future and a hope. (ESV)"], "query": "024029011"},
{"canonical" : "Titus 3:5", "passages": ["he saved us, not because of works done by us in righteousness, but according to his own mercy, by the washing of regeneration and renewal of the Holy Spirit, (ESV)"], "query": "056003005"},
{"canonical" : "Romans 12:2", "passages": ["Do not be conformed to this world, but be transformed by the renewal of your mind, that by testing you may discern what is the will of God, what is good and acceptable and perfect. (ESV)"], "query": "045012002"},
{"canonical" : "John 14:1", "passages": ["\"Let not your hearts be troubled. Believe in God; believe also in me. (ESV)"], "query": "043014001"},
{"canonical" : "Romans 5:12", "passages": ["Therefore, just as sin came into the world through one man, and death through sin, and so death spread to all men because all sinned-- (ESV)"], "query": "045005012"},
{"canonical" : "Matthew 11:28", "passages": ["Come to me, all who labor and are heavy laden, and I will give you rest. (ESV)"], "query": "040011028"},
{"canonical" : "Romans 5:1", "passages": ["Therefore, since we have been justified by faith, we have peace with God through our Lord Jesus Christ. (ESV)"], "query": "045005001"},
{"canonical" : "Genesis 1:27", "passages": ["So God created man in his own image, in the image of God he created him; male and female he created them. (ESV)"], "query": "001001027"},
{"canonical" : "Romans 1:16", "passages": ["For I am not ashamed of the gospel, for it is the power of God for salvation to everyone who believes, to the Jew first and also to the Greek. (ESV)"], "query": "045001016"},
{"canonical" : "Deuteronomy 6:4", "passages": ["\"Hear, O Israel: The LORD our God, the LORD is one. (ESV)"], "query": "005006004"},
{"canonical" : "1 John 1:9", "passages": ["If we confess our sins, he is faithful and just to forgive us our sins and to cleanse us from all unrighteousness. (ESV)"], "query": "062001009"},
{"canonical" : "2 Corinthians 5:17", "passages": ["Therefore, if anyone is in Christ, he is a new creation. The old has passed away; behold, the new has come. (ESV)"], "query": "047005017"},
{"canonical" : "Hebrews 11:1", "passages": ["Now faith is the assurance of things hoped for, the conviction of things not seen. (ESV)"], "query": "058011001"},
{"canonical" : "2 Timothy 2:15", "passages": ["Do your best to present yourself to God as one approved, a worker who has no need to be ashamed, rightly handling the word of truth. (ESV)"], "query": "055002015"},
{"canonical" : "Romans 8:1", "passages": ["There is therefore now no condemnation for those who are in Christ Jesus. (ESV)"], "query": "045008001"},
{"canonical" : "Romans 10:13", "passages": ["For \"everyone who calls on the name of the Lord will be saved.\" (ESV)"], "query": "045010013"},
{"canonical" : "John 8:32", "passages": ["and you will know the truth, and the truth will set you free.\" (ESV)"], "query": "043008032"},
{"canonical" : "Matthew 6:33", "passages": ["But seek first the kingdom of God and his righteousness, and all these things will be added to you. (ESV)"], "query": "040006033"},
{"canonical" : "Luke 4:18", "passages": ["\"The Spirit of the Lord is upon me, because he has anointed me to proclaim good news to the poor. He has sent me to proclaim liberty to the captives and recovering of sight to the blind, to set at liberty those who are oppressed, (ESV)"], "query": "042004018"},
{"canonical" : "John 16:13", "passages": ["When the Spirit of truth comes, he will guide you into all the truth, for he will not speak on his own authority, but whatever he hears he will speak, and he will declare to you the things that are to come. (ESV)"], "query": "043016013"},
{"canonical" : "Romans 3:10", "passages": ["as it is written: \"None is righteous, no, not one; (ESV)"], "query": "045003010"},
{"canonical" : "Hebrews 11:6", "passages": ["And without faith it is impossible to please him, for whoever would draw near to God must believe that he exists and that he rewards those who seek him. (ESV)"], "query": "058011006"},
{"canonical" : "Matthew 22:37", "passages": ["And he said to him, \"You shall love the Lord your God with all your heart and with all your soul and with all your mind. (ESV)"], "query": "040022037"},
{"canonical" : "Philippians 4:8", "passages": ["Finally, brothers, whatever is true, whatever is honorable, whatever is just, whatever is pure, whatever is lovely, whatever is commendable, if there is any excellence, if there is anything worthy of praise, think about these things. (ESV)"], "query": "050004008"},
{"canonical" : "Acts 16:31", "passages": ["And they said, \"Believe in the Lord Jesus, and you will be saved, you and your household.\" (ESV)"], "query": "044016031"},
{"canonical" : "John 15:5", "passages": ["I am the vine; you are the branches. Whoever abides in me and I in him, he it is that bears much fruit, for apart from me you can do nothing. (ESV)"], "query": "043015005"},
{"canonical" : "John 17:3", "passages": ["And this is eternal life, that they know you the only true God, and Jesus Christ whom you have sent. (ESV)"], "query": "043017003"},
{"canonical" : "Revelation 3:20", "passages": ["Behold, I stand at the door and knock. If anyone hears my voice and opens the door, I will come in to him and eat with him, and he with me. (ESV)"], "query": "066003020"},
{"canonical" : "Matthew 7:21", "passages": ["\"Not everyone who says to me, 'Lord, Lord,' will enter the kingdom of heaven, but the one who does the will of my Father who is in heaven. (ESV)"], "query": "040007021"},
{"canonical" : "Genesis 1:3", "passages": ["And God said, \"Let there be light,\" and there was light. (ESV)"], "query": "001001003"},
{"canonical" : "1 Peter 2:9", "passages": ["But you are a chosen race, a royal priesthood, a holy nation, a people for his own possession, that you may proclaim the excellencies of him who called you out of darkness into his marvelous light. (ESV)"], "query": "060002009"},
{"canonical" : "Matthew 5:14", "passages": ["\"You are the light of the world. A city set on a hill cannot be hidden. (ESV)"], "query": "040005014"},
{"canonical" : "Matthew 7:7", "passages": ["\"Ask, and it will be given to you; seek, and you will find; knock, and it will be opened to you. (ESV)"], "query": "040007007"},
{"canonical" : "Isaiah 9:6", "passages": ["For to us a child is born, to us a son is given; and the government shall be upon his shoulder, and his name shall be called Wonderful Counselor, Mighty God, Everlasting Father, Prince of Peace. (ESV)"], "query": "023009006"},
{"canonical" : "Hebrews 4:12", "passages": ["For the word of God is living and active, sharper than any two-edged sword, piercing to the division of soul and of spirit, of joints and of marrow, and discerning the thoughts and intentions of the heart. (ESV)"], "query": "058004012"},
{"canonical" : "Isaiah 7:14", "passages": ["Therefore the Lord himself will give you a sign. Behold, the virgin shall conceive and bear a son, and shall call his name Immanuel. (ESV)"], "query": "023007014"},
{"canonical" : "John 14:15", "passages": ["\"If you love me, you will keep my commandments. (ESV)"], "query": "043014015"},
{"canonical" : "John 15:1", "passages": ["\"I am the true vine, and my Father is the vinedresser. (ESV)"], "query": "043015001"},
{"canonical" : "John 13:34", "passages": ["A new commandment I give to you, that you love one another: just as I have loved you, you also are to love one another. (ESV)"], "query": "043013034"},
{"canonical" : "John 4:24", "passages": ["God is spirit, and those who worship him must worship in spirit and truth.\" (ESV)"], "query": "043004024"},
{"canonical" : "Ephesians 2:1", "passages": ["And you were dead in the trespasses and sins (ESV)"], "query": "049002001"},
{"canonical" : "John 14:16", "passages": ["And I will ask the Father, and he will give you another Helper, to be with you forever, (ESV)"], "query": "043014016"},
{"canonical" : "Genesis 1:2", "passages": ["The earth was without form and void, and darkness was over the face of the deep. And the Spirit of God was hovering over the face of the waters. (ESV)"], "query": "001001002"},
{"canonical" : "James 5:16", "passages": ["Therefore, confess your sins to one another and pray for one another, that you may be healed. The prayer of a righteous person has great power as it is working. (ESV)"], "query": "059005016"},
{"canonical" : "John 1:7", "passages": ["He came as a witness, to bear witness about the light, that all might believe through him. (ESV)"], "query": "043001007"},
{"canonical" : "John 3:5", "passages": ["Jesus answered, \"Truly, truly, I say to you, unless one is born of water and the Spirit, he cannot enter the kingdom of God. (ESV)"], "query": "043003005"},
{"canonical" : "Philippians 2:5", "passages": ["Have this mind among yourselves, which is yours in Christ Jesus, (ESV)"], "query": "050002005"},
{"canonical" : "John 1:29", "passages": ["The next day he saw Jesus coming toward him, and said, \"Behold, the Lamb of God, who takes away the sin of the world! (ESV)"], "query": "043001029"},
{"canonical" : "Romans 1:18", "passages": ["For the wrath of God is revealed from heaven against all ungodliness and unrighteousness of men, who by their unrighteousness suppress the truth. (ESV)"], "query": "045001018"},
{"canonical" : "Hebrews 12:1", "passages": ["Therefore, since we are surrounded by so great a cloud of witnesses, let us also lay aside every weight, and sin which clings so closely, and let us run with endurance the race that is set before us, (ESV)"], "query": "058012001"},
{"canonical" : "Matthew 16:18", "passages": ["And I tell you, you are Peter, and on this rock I will build my church, and the gates of hell shall not prevail against it. (ESV)"], "query": "040016018"},
{"canonical" : "Matthew 5:17", "passages": ["\"Do not think that I have come to abolish the Law or the Prophets; I have not come to abolish them but to fulfill them. (ESV)"], "query": "040005017"},
{"canonical" : "Romans 10:17", "passages": ["So faith comes from hearing, and hearing through the word of Christ. (ESV)"], "query": "045010017"},
{"canonical" : "Acts 20:28", "passages": ["Pay careful attention to yourselves and to all the flock, in which the Holy Spirit has made you overseers, to care for the church of God, which he obtained with his own blood. (ESV)"], "query": "044020028"},
{"canonical" : "Titus 2:11", "passages": ["For the grace of God has appeared, bringing salvation for all people, (ESV)"], "query": "056002011"},
{"canonical" : "Ephesians 6:10", "passages": ["Finally, be strong in the Lord and in the strength of his might. (ESV)"], "query": "049006010"},
{"canonical" : "Romans 13:1", "passages": ["Let every person be subject to the governing authorities. For there is no authority except from God, and those that exist have been instituted by God. (ESV)"], "query": "045013001"},
{"canonical" : "John 2:15", "passages": ["And making a whip of cords, he drove them all out of the temple, with the sheep and oxen. And he poured out the coins of the money-changers and overturned their tables. (ESV)"], "query": "043002015"},
{"canonical" : "Mark 16:16", "passages": ["Whoever believes and is baptized will be saved, but whoever does not believe will be condemned. (ESV)"], "query": "041016016"},
{"canonical" : "Genesis 3:15", "passages": ["I will put enmity between you and the woman, and between your offspring and her offspring; he shall bruise your head, and you shall bruise his heel.\" (ESV)"], "query": "001003015"},
{"canonical" : "John 14:26", "passages": ["But the Helper, the Holy Spirit, whom the Father will send in my name, he will teach you all things and bring to your remembrance all that I have said to you. (ESV)"], "query": "043014026"},
{"canonical" : "John 5:24", "passages": ["Truly, truly, I say to you, whoever hears my word and believes him who sent me has eternal life. He does not come into judgment, but has passed from death to life. (ESV)"], "query": "043005024"},
{"canonical" : "Joel 2:28", "passages": ["\"And it shall come to pass afterward, that I will pour out my Spirit on all flesh; your sons and your daughters shall prophesy, your old men shall dream dreams, and your young men shall see visions. (ESV)"], "query": "029002028"},
{"canonical" : "Genesis 1:11", "passages": ["And God said, \"Let the earth sprout vegetation, plants yielding seed, and fruit trees bearing fruit in which is their seed, each according to its kind, on the earth.\" And it was so. (ESV)"], "query": "001001011"},
{"canonical" : "James 1:2", "passages": ["Count it all joy, my brothers, when you meet trials of various kinds, (ESV)"], "query": "059001002"},
{"canonical" : "Colossians 1:15", "passages": ["He is the image of the invisible God, the firstborn of all creation. (ESV)"], "query": "051001015"},
{"canonical" : "Titus 2:13", "passages": ["waiting for our blessed hope, the appearing of the glory of our great God and Savior Jesus Christ, (ESV)"], "query": "056002013"},
{"canonical" : "Acts 1:9", "passages": ["And when he had said these things, as they were looking on, he was lifted up, and a cloud took him out of their sight. (ESV)"], "query": "044001009"},
{"canonical" : "John 4:7", "passages": ["There came a woman of Samaria to draw water. Jesus said to her, \"Give me a drink.\" (ESV)"], "query": "043004007"},
{"canonical" : "Micah 6:8", "passages": ["He has told you, O man, what is good; and what does the LORD require of you but to do justice, and to love kindness, and to walk humbly with your God? (ESV)"], "query": "033006008"},
{"canonical" : "John 17:17", "passages": ["Sanctify them in the truth; your word is truth. (ESV)"], "query": "043017017"},
{"canonical" : "John 11:25", "passages": ["Jesus said to her, \"I am the resurrection and the life. Whoever believes in me, though he die, yet shall he live, (ESV)"], "query": "043011025"},
{"canonical" : "John 8:58", "passages": ["Jesus said to them, \"Truly, truly, I say to you, before Abraham was, I am.\" (ESV)"], "query": "043008058"},
{"canonical" : "Acts 2:4", "passages": ["And they were all filled with the Holy Spirit and began to speak in other tongues as the Spirit gave them utterance. (ESV)"], "query": "044002004"},
{"canonical" : "Acts 2:41", "passages": ["So those who received his word were baptized, and there were added that day about three thousand souls. (ESV)"], "query": "044002041"},
{"canonical" : "Proverbs 22:6", "passages": ["Train up a child in the way he should go; even when he is old he will not depart from it. (ESV)"], "query": "020022006"},
{"canonical" : "Genesis 3:1", "passages": ["Now the serpent was more crafty than any other beast of the field that the LORD God had made.He said to the woman, \"Did God actually say, 'You shall not eat of any tree in the garden'?\" (ESV)"], "query": "001003001"},
{"canonical" : "James 1:5", "passages": ["If any of you lacks wisdom, let him ask God, who gives generously to all without reproach, and it will be given him. (ESV)"], "query": "059001005"},
{"canonical" : "Hebrews 1:1", "passages": ["Long ago, at many times and in many ways, God spoke to our fathers by the prophets, (ESV)"], "query": "058001001"},
{"canonical" : "Luke 1:4", "passages": ["that you may have certainty concerning the things you have been taught. (ESV)"], "query": "042001004"},
{"canonical" : "John 10:30", "passages": ["I and the Father are one.\" (ESV)"], "query": "043010030"},
{"canonical" : "1 Peter 3:15", "passages": ["but in your hearts regard Christ the Lord as holy, always being prepared to make a defense to anyone who asks you for a reason for the hope that is in you; (ESV)"], "query": "060003015"},
{"canonical" : "John 3:18", "passages": ["Whoever believes in him is not condemned, but whoever does not believe is condemned already, because he has not believed in the name of the only Son of God. (ESV)"], "query": "043003018"},
{"canonical" : "Genesis 12:1", "passages": ["Now the LORD said to Abram, \"Go from your country and your kindred and your father's house to the land that I will show you. (ESV)"], "query": "001012001"},
{"canonical" : "John 3:8", "passages": ["The wind blows where it wishes, and you hear its sound, but you do not know where it comes from or where it goes. So it is with everyone who is born of the Spirit.\" (ESV)"], "query": "043003008"},
{"canonical" : "Genesis 2:7", "passages": ["then the LORD God formed the man of dust from the ground and breathed into his nostrils the breath of life, and the man became a living creature. (ESV)"], "query": "001002007"},
{"canonical" : "John 8:12", "passages": ["Again Jesus spoke to them, saying, \"I am the light of the world. Whoever follows me will not walk in darkness, but will have the light of life.\" (ESV)"], "query": "043008012"},
{"canonical" : "Luke 1:26", "passages": ["In the sixth month the angel Gabriel was sent from God to a city of Galilee named Nazareth, (ESV)"], "query": "042001026"},
{"canonical" : "Hebrews 9:27", "passages": ["And just as it is appointed for man to die once, and after that comes judgment, (ESV)"], "query": "058009027"},
{"canonical" : "John 3:2", "passages": ["This man came to Jesus by night and said to him, \"Rabbi, we know that you are a teacher come from God, for no one can do these signs that you do unless God is with him.\" (ESV)"], "query": "043003002"},
{"canonical" : "Exodus 3:14", "passages": ["God said to Moses, \"I AM WHO I AM.\" And he said, \"Say this to the people of Israel, 'I AM has sent me to you.'\" (ESV)"], "query": "002003014"},
{"canonical" : "1 Corinthians 6:9", "passages": ["Do you not know that the unrighteous will not inherit the kingdom of God? Do not be deceived: neither the sexually immoral, nor idolaters, nor adulterers, nor men who practice homosexuality, (ESV)"], "query": "046006009"},
{"canonical" : "Luke 10:25", "passages": ["And behold, a lawyer stood up to put him to the test, saying, \"Teacher, what shall I do to inherit eternal life?\" (ESV)"], "query": "042010025"},
{"canonical" : "John 1:8", "passages": ["He was not the light, but came to bear witness about the light. (ESV)"], "query": "043001008"},
{"canonical" : "Ephesians 1:3", "passages": ["Blessed be the God and Father of our Lord Jesus Christ, who has blessed us in Christ with every spiritual blessing in the heavenly places, (ESV)"], "query": "049001003"},
{"canonical" : "Matthew 1:18", "passages": ["Now the birth of Jesus Christ took place in this way. When his mother Mary had been betrothed to Joseph, before they came together she was found to be with child from the Holy Spirit. (ESV)"], "query": "040001018"},
{"canonical" : "John 1:5", "passages": ["The light shines in the darkness, and the darkness has not overcome it. (ESV)"], "query": "043001005"},
{"canonical" : "1 Thessalonians 4:13", "passages": ["But we do not want you to be uninformed, brothers, about those who are asleep, that you may not grieve as others do who have no hope. (ESV)"], "query": "052004013"},
{"canonical" : "1 John 4:1", "passages": ["Beloved, do not believe every spirit, but test the spirits to see whether they are from God, for many false prophets have gone out into the world. (ESV)"], "query": "062004001"},
{"canonical" : "James 1:17", "passages": ["Every good gift and every perfect gift is from above, coming down from the Father of lights with whom there is no variation or shadow due to change. (ESV)"], "query": "059001017"},
{"canonical" : "John 3:1", "passages": ["Now there was a man of the Pharisees named Nicodemus, a ruler of the Jews. (ESV)"], "query": "043003001"},
{"canonical" : "Ephesians 4:11", "passages": ["And he gave the apostles, the prophets, the evangelists, the pastors and teachers, (ESV)"], "query": "049004011"},
{"canonical" : "Matthew 6:19", "passages": ["\"Do not lay up for yourselves treasures on earth, where moth and rust destroy and where thieves break in and steal, (ESV)"], "query": "040006019"},
{"canonical" : "Isaiah 61:1", "passages": ["The Spirit of the Lord GOD is upon me, because the LORD has anointed me to bring good news to the poor; he has sent me to bind up the brokenhearted, to proclaim liberty to the captives, and the opening of the prison to those who are bound; (ESV)"], "query": "023061001"},
{"canonical" : "Galatians 3:28", "passages": ["There is neither Jew nor Greek, there is neither slave nor free, there is neither male nor female, for you are all one in Christ Jesus. (ESV)"], "query": "048003028"},
{"canonical" : "2 Peter 3:9", "passages": ["The Lord is not slow to fulfill his promise as some count slowness, but is patient toward you, not wishing that any should perish, but that all should reach repentance. (ESV)"], "query": "061003009"},
{"canonical" : "Acts 1:11", "passages": ["and said, \"Men of Galilee, why do you stand looking into heaven? This Jesus, who was taken up from you into heaven, will come in the same way as you saw him go into heaven.\" (ESV)"], "query": "044001011"},
{"canonical" : "James 5:14", "passages": ["Is anyone among you sick? Let him call for the elders of the church, and let them pray over him, anointing him with oil in the name of the Lord. (ESV)"], "query": "059005014"},
{"canonical" : "John 3:36", "passages": ["Whoever believes in the Son has eternal life; whoever does not obey the Son shall not see life, but the wrath of God remains on him. (ESV)"], "query": "043003036"},
{"canonical" : "Ephesians 6:12", "passages": ["For we do not wrestle against flesh and blood, but against the rulers, against the authorities, against the cosmic powers over this present darkness, against the spiritual forces of evil in the heavenly places. (ESV)"], "query": "049006012"},
{"canonical" : "Matthew 6:9", "passages": ["Pray then like this: \"Our Father in heaven, hallowed be your name. (ESV)"], "query": "040006009"},
{"canonical" : "Acts 3:19", "passages": ["Repent therefore, and turn again, that your sins may be blotted out, (ESV)"], "query": "044003019"},
{"canonical" : "James 2:14", "passages": ["What good is it, my brothers, if someone says he has faith but does not have works? Can that faith save him? (ESV)"], "query": "059002014"},
{"canonical" : "Isaiah 40:31", "passages": ["but they who wait for the LORD shall renew their strength; they shall mount up with wings like eagles; they shall run and not be weary; they shall walk and not faint. (ESV)"], "query": "023040031"},
{"canonical" : "John 3:17", "passages": ["For God did not send his Son into the world to condemn the world, but in order that the world might be saved through him. (ESV)"], "query": "043003017"},
{"canonical" : "Luke 1:35", "passages": ["And the angel answered her, \"The Holy Spirit will come upon you, and the power of the Most High will overshadow you; therefore the child to be born will be called holy--the Son of God. (ESV)"], "query": "042001035"},
{"canonical" : "Genesis 1:28", "passages": ["And God blessed them. And God said to them, \"Be fruitful and multiply and fill the earth and subdue it and have dominion over the fish of the sea and over the birds of the heavens and over every living thing that moves on the earth.\" (ESV)"], "query": "001001028"},
{"canonical" : "Ephesians 2:10", "passages": ["For we are his workmanship, created in Christ Jesus for good works, which God prepared beforehand, that we should walk in them. (ESV)"], "query": "049002010"},
{"canonical" : "2 Corinthians 5:21", "passages": ["For our sake he made him to be sin who knew no sin, so that in him we might become the righteousness of God. (ESV)"], "query": "047005021"},
{"canonical" : "Romans 6:1", "passages": ["What shall we say then? Are we to continue in sin that grace may abound? (ESV)"], "query": "045006001"},
{"canonical" : "Ephesians 1:13", "passages": ["In him you also, when you heard the word of truth, the gospel of your salvation, and believed in him, were sealed with the promised Holy Spirit, (ESV)"], "query": "049001013"},
{"canonical" : "Romans 6:3", "passages": ["Do you not know that all of us who have been baptized into Christ Jesus were baptized into his death? (ESV)"], "query": "045006003"}
]}

   //ketiv is indicated in brackets or omitted
